export const productsMock = [
  {
    id: "nem-cao-su-1",
    name: "Nệm Cao Su Thiên Nhiên Thắng Lợi",
    price: 12500000,
    originalPrice: 15000000,
    discountPercent: 17,
    image: "/prod-1.webp",
    hoverImage: "/prod-2.webp",
    badge: "New",
  },
  {
    id: "nem-cao-su-2",
    name: "Nệm Cao Su Premium Massage",
    price: 14800000,
    originalPrice: 15000000,
    discountPercent: 17,
    image: "/prod-2.webp",
    hoverImage: "/prod-1.webp",
  },
  {
    id: "nem-cao-su-3",
    name: "Nệm Cao Su Trẻ Em",
    price: 7200000,
    originalPrice: 15000000,
    discountPercent: 17,
    image: "/prod-1.webp",
    hoverImage: "/prod-2.webp",
    badge: "Sale",
  },
  {
    id: "nem-lo-xo-1",
    name: "Nệm Lò Xo Túi Độc Lập",
    price: 6900000,
    originalPrice: 15000000,
    discountPercent: 17,
    image: "/prod-1.webp",
    hoverImage: "/prod-2.webp",
  },
  {
    id: "nem-lo-xo-2",
    name: "Nệm Lò Xo Cao Cấp Khách Sạn",
    price: 11500000,
    originalPrice: 15000000,
    discountPercent: 17,
    image: "/prod-2.webp",
    hoverImage: "/prod-1.webp",
    badge: "New",
  },
  {
    id: "nem-bong-ep-1",
    name: "Nệm Bông Ép Cao Cấp",
    price: 3500000,
    originalPrice: 15000000,
    discountPercent: 17,
    image: "/prod-1.webp",
    hoverImage: "/prod-1.webp",
  },
  {
    id: "nem-bong-ep-2",
    name: "Nệm Bông Ép Gấp 3",
    price: 4200000,
    originalPrice: 15000000,
    discountPercent: 17,
    image: "/prod-1.webp",
    hoverImage: "/prod-2.webp",
    badge: "Sale",
  },
  {
    id: "nem-khach-san-1",
    name: "Nệm Khách Sạn 5 Sao",
    price: 16800000,
    originalPrice: 15000000,
    discountPercent: 17,
    image: "/prod-2.webp",
    hoverImage: "/prod-1.webp",
  },
  {
    id: "nem-khach-san-2",
    name: "Nệm Khách Sạn Cao Su + Lò Xo",
    price: 18500000,
    originalPrice: 15000000,
    discountPercent: 17,
    image: "/prod-1.webp",
    hoverImage: "/prod-1.webp",
  },
  {
    id: "nem-cao-su-orthopedic",
    name: "Nệm Cao Su Hỗ Trợ Cột Sống",
    price: 13200000,
    originalPrice: 15000000,
    discountPercent: 17,
    image: "/prod-1.webp",
    hoverImage: "/prod-2.webp",
    badge: "Hot",
  },

  // ===== 10 sản phẩm tiếp =====

  {
    id: "goi-cao-su-1",
    name: "Gối Cao Su Thiên Nhiên",
    price: 950000,
    image: "/prod-2.webp",
    hoverImage: "/prod-1.webp",
  },
  {
    id: "goi-cao-su-2",
    name: "Gối Cao Su Massage",
    price: 1250000,
    image: "/prod-1.webp",
    hoverImage: "/prod-1.webp",
  },
  {
    id: "nem-gap-1",
    name: "Nệm Gấp Văn Phòng",
    price: 2800000,
    image: "/prod-1.webp",
    hoverImage: "/prod-2.webp",
    badge: "Sale",
  },
  {
    id: "nem-gap-2",
    name: "Nệm Gấp Du Lịch",
    price: 3100000,
    image: "/prod-2.webp",
    hoverImage: "/prod-1.webp",
  },
  {
    id: "nem-cao-su-massage",
    name: "Nệm Cao Su Massage Toàn Thân",
    price: 15500000,
    image: "/prod-1.webp",
    hoverImage: "/prod-1.webp",
    badge: "New",
  },
  {
    id: "nem-lo-xo-lien-ket",
    name: "Nệm Lò Xo Liên Kết",
    price: 5900000,
    image: "/prod-1.webp",
    hoverImage: "/prod-2.webp",
  },
  {
    id: "nem-tre-em-foam",
    name: "Nệm Foam Trẻ Em",
    price: 4800000,
    image: "/prod-2.webp",
    hoverImage: "/prod-1.webp",
  },
  {
    id: "nem-foam-1",
    name: "Nệm Foam Memory",
    price: 8800000,
    image: "/prod-1.webp",
    hoverImage: "/prod-1.webp",
  },
  {
    id: "nem-foam-2",
    name: "Nệm Foam Cao Cấp",
    price: 10200000,
    image: "/prod-1.webp",
    hoverImage: "/prod-2.webp",
  },
  {
    id: "nem-dac-biet",
    name: "Nệm Cao Su Đặc Biệt Thắng Lợi",
    price: 19800000,
    image: "/prod-2.webp",
    hoverImage: "/prod-1.webp",
    badge: "Hot",
  },
];
