export const productDetailMap = {
  "nem-cao-su-1": {
    id: "nem-cao-su-1",
    name: "Nệm Cao Su Thiên Nhiên Thắng Lợi",
    price: 12500000,
    originalPrice: 15000000,
    discountPercent: 17,
    badge: "New",
    sizes: ["1m x 2m", "1m2 x 2m", "1m4 x 2m"],
    colors: ["#f5c7c7", "#2f2f2f", "#1e3a8a"],
    images: [
      "/bg_nemthangloi1.png",
      "/bg_nemthangloi2.png",
      "/bg_nemthangloi3.png",
    ],
    description: "Nệm cao su thiên nhiên 100%, đàn hồi tốt...",
  },
  "nem-cao-su-2": {
    id: "nem-cao-su-2",
    name: "Nệm Cao Su Premium Massage",
    price: 14800000,
    originalPrice: 11000000,
    discountPercent: 11,
    badge: "Hot",
    sizes: ["1m x 2m", "1m2 x 2m", "1m4 x 2m"],
    colors: ["#e5e7eb", "#111827"],
    images: [
      "/bg_nemthangloi1.png",
      "/bg_nemthangloi2.png",
      "/bg_nemthangloi3.png",
    ],
    description: "Phiên bản cao cấp, nâng đỡ tối ưu...",
  },
  "nem-cao-su-3": {
    id: "nem-cao-su-3",
    name: "Nệm Cao Su Trẻ Em",
    price: 9800000,
    originalPrice: 11000000,
    discountPercent: 11,
    badge: "Hot",
    sizes: ["1m x 2m", "1m2 x 2m", "1m4 x 2m"],
    colors: ["#e5e7eb", "#111827"],
    images: [
      "/bg_nemthangloi1.png",
      "/bg_nemthangloi2.png",
      "/bg_nemthangloi3.png",
    ],
    description: "Phiên bản cao cấp, nâng đỡ tối ưu...",
  },
  "nem-lo-xo-1": {
    id: "nem-lo-xo-1",
    name: "Nệm Lò Xo Túi Độc Lập",
    price: 9800000,
    originalPrice: 11000000,
    discountPercent: 11,
    badge: "Hot",
    sizes: ["1m x 2m", "1m2 x 2m", "1m4 x 2m"],
    colors: ["#e5e7eb", "#111827"],
    images: [
      "/bg_nemthangloi1.png",
      "/bg_nemthangloi2.png",
      "/bg_nemthangloi3.png",
    ],
    description: "Phiên bản cao cấp, nâng đỡ tối ưu...",
  },
};

export const relatedProducts = [
  {
    id: "nem-lo-xo",
    name: "Nệm Lò Xo Túi",
    price: 6900000,
    image: "/bg_nemthangloi2.png",
    badge: "Sale",
  },
  {
    id: "nem-bong-ep",
    name: "Nệm Bông",
    price: 3500000,
    image: "/bg_nemthangloi3.png",
  },
  {
    id: "nem-bong-ep",
    name: "Nệm Bông Ép",
    price: 3500000,
    image: "/bg_nemthangloi3.png",
  },
  {
    id: "nem-bong-ep",
    name: "Nệm cao su",
    price: 3500000,
    image: "/bg_nemthangloi3.png",
  },
];
